#!/usr/bin/env python3
"""
AMA Synthetic Dataset Generator
--------------------------------
Generates parameterized synthetic analytics data for the AMA PostgreSQL schema.

Outputs:
- SQL INSERT script
OR
- CSV files for bulk load

Supported tables:
- ama.brand
- ama.category
- ama.product
- ama.dim_date
- ama.fact_sales_daily
- ama.fact_traffic_daily
- ama.fact_inventory_daily
- ama.fact_finance_daily

Example:
python ama_synthetic_data_generator.py \
  --tenant-id 1 \
  --account-id 1 \
  --num-products 1000 \
  --months 12 \
  --output-format sql \
  --output-dir ./out

Notes:
- Assumes tenant / account rows already exist.
- category_id / brand_id / product_id are explicitly generated by this script.
- Good for local dev, MCP/tool testing, and agent query prototyping.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import random
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


# -----------------------------
# Config / domain model
# -----------------------------

CATEGORIES = {
    "Laptops": {
        "brands": ["HP", "Dell", "Lenovo", "Asus", "Acer"],
        "price_range": (35000, 145000),
        "daily_unit_range": (0, 12),
    },
    "Monitors": {
        "brands": ["LG", "Samsung", "Dell", "Acer", "BenQ"],
        "price_range": (8000, 45000),
        "daily_unit_range": (0, 8),
    },
    "Keyboards": {
        "brands": ["Logitech", "HP", "Dell", "Redragon", "Corsair"],
        "price_range": (700, 6500),
        "daily_unit_range": (0, 15),
    },
    "Mouse": {
        "brands": ["Logitech", "HP", "Dell", "Razer", "Redragon"],
        "price_range": (500, 4500),
        "daily_unit_range": (0, 18),
    },
    "Printers": {
        "brands": ["HP", "Canon", "Epson", "Brother"],
        "price_range": (5000, 30000),
        "daily_unit_range": (0, 4),
    },
    "Routers": {
        "brands": ["TP-Link", "Netgear", "D-Link", "Asus"],
        "price_range": (1200, 12000),
        "daily_unit_range": (0, 7),
    },
    "Tablets": {
        "brands": ["Samsung", "Lenovo", "Apple", "Xiaomi"],
        "price_range": (9000, 75000),
        "daily_unit_range": (0, 6),
    },
    "External SSD": {
        "brands": ["Samsung", "WD", "SanDisk", "Seagate"],
        "price_range": (3500, 18000),
        "daily_unit_range": (0, 9),
    },
    "Desktop PCs": {
        "brands": ["HP", "Dell", "Lenovo", "Acer"],
        "price_range": (28000, 120000),
        "daily_unit_range": (0, 5),
    },
    "Headphones": {
        "brands": ["Sony", "JBL", "Boat", "Logitech", "Razer"],
        "price_range": (800, 15000),
        "daily_unit_range": (0, 14),
    },
}

ADJECTIVES = [
    "Ultra", "Smart", "Pro", "Prime", "Elite", "Max", "Air", "Vision",
    "Turbo", "Nova", "Flex", "Edge", "Swift", "Zen", "Fusion"
]

SPEC_HINTS = {
    "Laptops": ["i5 8GB 512GB", "i7 16GB 512GB", "Ryzen 5 16GB 1TB", "i3 8GB 256GB"],
    "Monitors": ["24 inch FHD", "27 inch QHD", "32 inch 4K", "24 inch IPS"],
    "Keyboards": ["Mechanical RGB", "Wireless", "Compact", "Full-size"],
    "Mouse": ["Wireless", "Gaming", "Silent Click", "Ergonomic"],
    "Printers": ["Ink Tank", "Laser Mono", "All-in-One", "Duplex"],
    "Routers": ["Dual Band", "Wi-Fi 6", "Mesh Ready", "AC1200"],
    "Tablets": ["10 inch WiFi", "11 inch LTE", "8 inch WiFi", "Stylus Support"],
    "External SSD": ["500GB USB-C", "1TB USB-C", "2TB USB 3.2", "1TB Rugged"],
    "Desktop PCs": ["i5 Tower", "i7 Tower", "Ryzen 7", "Mini PC"],
    "Headphones": ["ANC", "Wireless", "Gaming", "Over-Ear"],
}


@dataclass
class Product:
    product_id: int
    tenant_id: int
    account_id: int | None
    asin: str
    sku: str
    product_name: str
    short_description: str
    brand_id: int
    category_id: int
    product_type: str
    price_amount: float
    currency_code: str
    rating_avg: float
    review_count: int
    is_active: bool
    launched_at: date


# -----------------------------
# Utility functions
# -----------------------------

def daterange(start_date: date, end_date: date) -> Iterable[date]:
    cur = start_date
    while cur <= end_date:
        yield cur
        cur += timedelta(days=1)


def date_key(d: date) -> int:
    return int(d.strftime("%Y%m%d"))


def sql_quote(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, date):
        return f"'{value.isoformat()}'"
    s = str(value).replace("'", "''")
    return f"'{s}'"


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def month_seasonality(d: date) -> float:
    # festive bump in Oct-Dec, mild bump in Jun
    seasonal = {
        1: 0.92, 2: 0.95, 3: 1.00, 4: 0.98, 5: 1.02, 6: 1.08,
        7: 1.00, 8: 1.03, 9: 1.06, 10: 1.18, 11: 1.28, 12: 1.35
    }
    return seasonal.get(d.month, 1.0)


def weekday_factor(d: date) -> float:
    # weekends slightly stronger for electronics retail browsing
    return 1.10 if d.weekday() >= 5 else 1.0


def build_dim_date_rows(start_date: date, end_date: date):
    rows = []
    for d in daterange(start_date, end_date):
        rows.append({
            "date_key": date_key(d),
            "full_date": d,
            "year_num": d.year,
            "quarter_num": ((d.month - 1) // 3) + 1,
            "month_num": d.month,
            "month_name": d.strftime("%B"),
            "week_num": int(d.strftime("%U")),
            "day_num": d.day,
            "day_name": d.strftime("%A"),
            "is_weekend": d.weekday() >= 5,
            "is_month_start": d.day == 1,
            "is_month_end": (d + timedelta(days=1)).month != d.month,
        })
    return rows


# -----------------------------
# Generators
# -----------------------------

def generate_master_data(
    tenant_id: int,
    account_id: int | None,
    num_products: int,
    seed: int,
    category_mix: Dict[str, float] | None = None,
):
    random.seed(seed)

    category_names = list(CATEGORIES.keys())
    if not category_mix:
        category_mix = {k: 1.0 / len(category_names) for k in category_names}

    # categories
    categories = []
    category_id_map = {}
    next_category_id = tenant_id * 100000 + 1
    for idx, cat_name in enumerate(category_names, start=1):
        category_id = next_category_id + idx - 1
        category_id_map[cat_name] = category_id
        categories.append({
            "category_id": category_id,
            "tenant_id": tenant_id,
            "category_code": cat_name.upper().replace(" ", "_"),
            "category_name": cat_name,
            "parent_category_id": None,
            "category_level": 1,
        })

    # brands
    all_brands = sorted({b for conf in CATEGORIES.values() for b in conf["brands"]})
    brands = []
    brand_id_map = {}
    next_brand_id = tenant_id * 100000 + 1
    for idx, brand_name in enumerate(all_brands, start=1):
        brand_id = next_brand_id + idx - 1
        brand_id_map[brand_name] = brand_id
        brands.append({
            "brand_id": brand_id,
            "tenant_id": tenant_id,
            "brand_code": brand_name.upper().replace(" ", "_"),
            "brand_name": brand_name,
        })

    # products
    products: List[Product] = []
    next_product_id = tenant_id * 1000000 + 1

    weighted_categories = []
    for c, w in category_mix.items():
        weighted_categories.extend([c] * max(1, int(w * 100)))

    for i in range(num_products):
        cat = random.choice(weighted_categories)
        conf = CATEGORIES[cat]
        brand = random.choice(conf["brands"])
        spec = random.choice(SPEC_HINTS[cat])
        adjective = random.choice(ADJECTIVES)
        model_no = f"{random.randint(100,999)}{random.choice(['X','Z','A','P'])}"
        product_name = f"{brand} {adjective} {cat} {model_no} {spec}"
        price = round(random.uniform(*conf["price_range"]), 2)

        product_id = next_product_id + i
        asin = f"B{tenant_id:02d}{product_id:08d}"[:10]
        sku = f"AMA-{tenant_id}-{product_id}"
        launched = date.today() - timedelta(days=random.randint(30, 900))

        products.append(Product(
            product_id=product_id,
            tenant_id=tenant_id,
            account_id=account_id,
            asin=asin,
            sku=sku,
            product_name=product_name,
            short_description=f"{cat} from {brand}, {spec}",
            brand_id=brand_id_map[brand],
            category_id=category_id_map[cat],
            product_type=cat,
            price_amount=price,
            currency_code="INR",
            rating_avg=round(random.uniform(3.6, 4.8), 2),
            review_count=random.randint(0, 2500),
            is_active=True,
            launched_at=launched,
        ))

    return brands, categories, products


def generate_fact_rows(
    tenant_id: int,
    account_id: int | None,
    products: List[Product],
    start_date: date,
    end_date: date,
    seed: int,
    marketplace_code: str = "IN",
):
    random.seed(seed + 999)

    sales_rows = []
    traffic_rows = []
    inventory_rows = []
    finance_rows = []

    for p in products:
        conf = CATEGORIES[p.product_type]
        min_units, max_units = conf["daily_unit_range"]

        # product popularity profile
        popularity = random.uniform(0.4, 2.6)
        # some hero products
        if random.random() < 0.08:
            popularity *= random.uniform(2.0, 4.0)

        inventory_level = random.randint(20, 250)

        for d in daterange(start_date, end_date):
            season = month_seasonality(d)
            weekday = weekday_factor(d)
            trend = 1.0 + ((d - start_date).days / max(1, (end_date - start_date).days)) * random.uniform(-0.15, 0.25)
            noise = random.uniform(0.65, 1.35)

            expected_units = popularity * season * weekday * trend * noise
            expected_units *= random.uniform(min_units + 0.3, max_units + 0.8)
            units_sold = int(max(0, round(expected_units / max_units)))

            # keep realistic
            units_sold = clamp(units_sold, 0, max_units * 3)

            orders_count = max(0, math.ceil(units_sold / random.uniform(1.0, 2.8))) if units_sold > 0 else 0
            gross_sales = round(units_sold * p.price_amount, 2)
            discount = round(gross_sales * random.uniform(0.00, 0.08), 2)
            net_sales = round(gross_sales - discount, 2)
            returned_units = 1 if units_sold > 0 and random.random() < 0.03 else 0
            returned_amount = round(returned_units * p.price_amount * random.uniform(0.8, 1.0), 2)
            avg_price = round(net_sales / units_sold, 2) if units_sold > 0 else p.price_amount

            sessions = int(max(0, units_sold * random.uniform(8, 24) + random.uniform(0, 50)))
            page_views = int(max(sessions, sessions * random.uniform(1.1, 2.8)))
            conversion = round((units_sold / sessions) * 100, 4) if sessions > 0 else 0.0
            buy_box = round(random.uniform(75.0, 99.0), 2)

            opening_stock = inventory_level
            inbound = random.randint(0, 80) if inventory_level < 30 and random.random() < 0.30 else 0
            reserved = random.randint(0, min(5, max(0, opening_stock)))
            damaged = random.randint(0, 2) if random.random() < 0.05 else 0
            closing_stock = max(0, opening_stock + inbound - units_sold - damaged)
            sellable = max(0, closing_stock - reserved)
            avg_daily_sale = max(0.1, popularity * (max_units / 5.0))
            days_of_cover = round(sellable / avg_daily_sale, 2)
            low_stock = sellable < max(5, int(avg_daily_sale * 3))
            out_of_stock = sellable == 0
            inventory_level = closing_stock

            fee_amount = round(net_sales * random.uniform(0.05, 0.09), 2)
            commission_amount = round(net_sales * random.uniform(0.05, 0.12), 2)
            fulfillment_fee = round(units_sold * random.uniform(15, 120), 2) if units_sold > 0 else 0
            storage_fee = round(max(0, closing_stock) * random.uniform(0.3, 2.2), 2)
            refund_amount = round(returned_amount, 2)
            adjustment_amount = round(random.uniform(-50, 50), 2) if random.random() < 0.03 else 0.0
            payout = round(net_sales - fee_amount - commission_amount - fulfillment_fee - storage_fee - refund_amount + adjustment_amount, 2)
            est_profit = round(net_sales * random.uniform(0.06, 0.22) - refund_amount, 2)

            dk = date_key(d)

            sales_rows.append({
                "tenant_id": tenant_id,
                "account_id": account_id,
                "product_id": p.product_id,
                "date_key": dk,
                "marketplace_code": marketplace_code,
                "units_sold": units_sold,
                "orders_count": orders_count,
                "gross_sales_amount": gross_sales,
                "discount_amount": discount,
                "net_sales_amount": net_sales,
                "returned_units": returned_units,
                "returned_amount": returned_amount,
                "avg_selling_price": avg_price,
            })

            traffic_rows.append({
                "tenant_id": tenant_id,
                "account_id": account_id,
                "product_id": p.product_id,
                "date_key": dk,
                "marketplace_code": marketplace_code,
                "sessions_count": sessions,
                "page_views_count": page_views,
                "buy_box_percentage": buy_box,
                "unit_session_percentage": conversion,
                "browser_sessions": int(sessions * random.uniform(0.45, 0.75)),
                "mobile_app_sessions": int(sessions * random.uniform(0.25, 0.55)),
                "browser_page_views": int(page_views * random.uniform(0.45, 0.75)),
                "mobile_app_page_views": int(page_views * random.uniform(0.25, 0.55)),
            })

            inventory_rows.append({
                "tenant_id": tenant_id,
                "account_id": account_id,
                "product_id": p.product_id,
                "date_key": dk,
                "marketplace_code": marketplace_code,
                "opening_stock_qty": opening_stock,
                "closing_stock_qty": closing_stock,
                "inbound_qty": inbound,
                "reserved_qty": reserved,
                "damaged_qty": damaged,
                "sellable_qty": sellable,
                "days_of_cover": days_of_cover,
                "low_stock_flag": low_stock,
                "out_of_stock_flag": out_of_stock,
            })

            finance_rows.append({
                "tenant_id": tenant_id,
                "account_id": account_id,
                "product_id": p.product_id,
                "date_key": dk,
                "marketplace_code": marketplace_code,
                "fee_amount": fee_amount,
                "commission_amount": commission_amount,
                "fulfillment_fee_amount": fulfillment_fee,
                "storage_fee_amount": storage_fee,
                "refund_amount": refund_amount,
                "adjustment_amount": adjustment_amount,
                "payout_amount": payout,
                "estimated_profit_amount": est_profit,
            })

    return sales_rows, traffic_rows, inventory_rows, finance_rows


# -----------------------------
# Writers
# -----------------------------

def write_csv(path: Path, rows: List[dict]):
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def insert_statement(table_name: str, rows: List[dict]) -> str:
    if not rows:
        return f"-- No rows for {table_name}\n"
    cols = list(rows[0].keys())
    lines = [f"INSERT INTO {table_name} ({', '.join(cols)}) VALUES"]
    value_lines = []
    for row in rows:
        vals = [sql_quote(row[c]) for c in cols]
        value_lines.append("(" + ", ".join(vals) + ")")
    lines.append(",\n".join(value_lines) + ";\n")
    return "\n".join(lines)


def write_sql(output_path: Path, brands, categories, products, dim_dates, sales, traffic, inventory, finance):
    output_path.parent.mkdir(parents=True, exist_ok=True)

    product_rows = [{
        "product_id": p.product_id,
        "tenant_id": p.tenant_id,
        "account_id": p.account_id,
        "asin": p.asin,
        "sku": p.sku,
        "product_name": p.product_name,
        "short_description": p.short_description,
        "brand_id": p.brand_id,
        "category_id": p.category_id,
        "product_type": p.product_type,
        "price_amount": p.price_amount,
        "currency_code": p.currency_code,
        "rating_avg": p.rating_avg,
        "review_count": p.review_count,
        "is_active": p.is_active,
        "launched_at": p.launched_at,
    } for p in products]

    with output_path.open("w", encoding="utf-8") as f:
        f.write("-- AMA Synthetic Seed Data\n")
        f.write("-- Generated by ama_synthetic_data_generator.py\n\n")
        f.write("BEGIN;\n\n")
        f.write(insert_statement("ama.brand", brands))
        f.write(insert_statement("ama.category", categories))
        f.write(insert_statement("ama.product", product_rows))
        f.write(insert_statement("ama.dim_date", dim_dates))
        f.write(insert_statement("ama.fact_sales_daily", sales))
        f.write(insert_statement("ama.fact_traffic_daily", traffic))
        f.write(insert_statement("ama.fact_inventory_daily", inventory))
        f.write(insert_statement("ama.fact_finance_daily", finance))
        f.write("COMMIT;\n")


# -----------------------------
# Main
# -----------------------------

def parse_args():
    parser = argparse.ArgumentParser(description="Generate synthetic data for AMA PostgreSQL schema.")
    parser.add_argument("--tenant-id", type=int, required=True, help="Tenant ID to generate data for.")
    parser.add_argument("--account-id", type=int, default=None, help="Optional marketplace account ID.")
    parser.add_argument("--num-products", type=int, default=1000, help="Number of products to generate.")
    parser.add_argument("--months", type=int, default=12, help="Number of months of daily facts to generate.")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility.")
    parser.add_argument("--output-format", choices=["sql", "csv"], default="sql", help="Output format.")
    parser.add_argument("--output-dir", default="./ama_synth_out", help="Output directory.")
    parser.add_argument("--marketplace-code", default="IN", help="Marketplace code, e.g. IN, US.")
    return parser.parse_args()


def main():
    args = parse_args()

    output_dir = Path(args.output_dir)
    end_date = date.today()
    start_date = end_date - timedelta(days=args.months * 30)

    brands, categories, products = generate_master_data(
        tenant_id=args.tenant_id,
        account_id=args.account_id,
        num_products=args.num_products,
        seed=args.seed,
    )

    dim_dates = build_dim_date_rows(start_date, end_date)
    sales, traffic, inventory, finance = generate_fact_rows(
        tenant_id=args.tenant_id,
        account_id=args.account_id,
        products=products,
        start_date=start_date,
        end_date=end_date,
        seed=args.seed,
        marketplace_code=args.marketplace_code,
    )

    if args.output_format == "csv":
        write_csv(output_dir / "brand.csv", brands)
        write_csv(output_dir / "category.csv", categories)
        write_csv(output_dir / "product.csv", [{
            "product_id": p.product_id,
            "tenant_id": p.tenant_id,
            "account_id": p.account_id,
            "asin": p.asin,
            "sku": p.sku,
            "product_name": p.product_name,
            "short_description": p.short_description,
            "brand_id": p.brand_id,
            "category_id": p.category_id,
            "product_type": p.product_type,
            "price_amount": p.price_amount,
            "currency_code": p.currency_code,
            "rating_avg": p.rating_avg,
            "review_count": p.review_count,
            "is_active": p.is_active,
            "launched_at": p.launched_at,
        } for p in products])
        write_csv(output_dir / "dim_date.csv", dim_dates)
        write_csv(output_dir / "fact_sales_daily.csv", sales)
        write_csv(output_dir / "fact_traffic_daily.csv", traffic)
        write_csv(output_dir / "fact_inventory_daily.csv", inventory)
        write_csv(output_dir / "fact_finance_daily.csv", finance)
        print(f"CSV files written to: {output_dir}")
    else:
        out_file = output_dir / f"ama_seed_tenant_{args.tenant_id}.sql"
        write_sql(out_file, brands, categories, products, dim_dates, sales, traffic, inventory, finance)
        print(f"SQL seed file written to: {out_file}")


if __name__ == "__main__":
    main()
